language: node_js
node_js:
  - 4.20
before_script:
  - npm install -g gulp
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-14.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-14.04.tar.bz2
  - ls -al
after_script:
  - node mail.js
os: 
  - osx
